name: Build and Deploy to Uberspace

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 25.2.1
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Svelte app
        run: npm run build
        env:
          PUBLIC_PB_URL: ${{ secrets.PUBLIC_PB_URL }}
      - name: list
        run: |
          ls -la build
          ls

      - name: Copy package.json and package-lock.json
        uses: burnett01/rsync-deployments@8.0.2
        with:
          switches: -avrh
          path: |
            package.json
            package-lock.json
          remote_path: /home/${{ vars.SSH_USERNAME }}/share-mvp/
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_PRIVATE_KEY_PASS }}

      - name: Install dependencies on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "
            cd /home/${{ vars.SSH_USERNAME }}/share-mvp/build &&
            npm ci --omit=dev
          "

      - name: Deploy using Rsync
        uses: burnett01/rsync-deployments@8.0.2
        with:
          switches: -avrh --delete
          path: |
            build/
          remote_path: /home/${{ vars.SSH_USERNAME }}/share-mvp/build
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_PRIVATE_KEY_PASS }}
